"""Write the road networks into the addon as Data/Roads.lua."""

from __future__ import annotations

import json
import time
from pathlib import Path


def roads_lua(data_dir: Path, continents=None) -> str:
    """ns.Roads[continent] = { n = {x1, y1, x2, y2, ...}, e = { {a, b, len, x, y, x, y, ...}, ... } }

    Node indices are 1-based; each edge's points run from node a to node b
    (world yards, X north / Y west).
    """
    if continents is None:
        from ..extract.pipeline import CONTINENTS as continents  # the shared list
    out = ["-- GENERATED by `agps roads` / `agps gen-addon-data`. Do not edit by hand.",
           "-- Road network per continent, extracted from terrain textures plus overrides/.",
           "local _, ns = ...", "ns.Roads = {"]
    for cont in continents:
        path = Path(data_dir) / f"roads_{cont}.json"
        if not path.exists():
            continue
        doc = json.loads(path.read_text(encoding="utf-8"))
        out.append(f"  -- build {doc.get('build')}, {len(doc['nodes'])} nodes, {len(doc['edges'])} edges")
        out.append(f"  [{cont}] = {{")
        flat = ",".join(f"{x:g},{y:g}" for x, y in doc["nodes"])
        out.append(f"    n = {{{flat}}},")
        out.append("    e = {")
        for e in doc["edges"]:
            pts = ",".join(f"{x:g},{y:g}" for x, y in e["pts"])
            src = {"terrain": 0, "bridge": 1, "override": 2}.get(e.get("src"), 0)
            out.append(f"      {{{e['a'] + 1},{e['b'] + 1},{e['len']:g},{src},{pts}}},")
        out.append("    },")
        out.append("  },")
    out.append("}")
    from ..paths import RESOURCES
    from .tracks import shipped_times

    from .tracks import walls

    ws = walls(RESOURCES / "overrides")
    out.append("-- walls drawn in game (what can't be walked through, like a mountain): per continent, point lists")
    out.append("ns.Walls = {")
    for cont in sorted(ws):
        out.append(f"  [{cont}] = {{")
        for w in ws[cont]:
            out.append("    {" + ",".join(f"{x:g},{y:g}" for x, y in w) + "},")
        out.append("  },")
    out.append("}")
    from .tracks import wall_opens

    opens = wall_opens(RESOURCES / "overrides")
    out.append("-- wall erasers drawn in game: they open the terrain's blocked ground under them")
    out.append("ns.WallOpens = {")
    for cont in sorted(opens):
        out.append(f"  [{cont}] = {{")
        for o in opens[cont]:
            pts = ",".join(f"{x:g},{y:g}" for x, y in o["pts"])
            out.append(f"    {{ area = {'true' if o['area'] else 'false'}, pts = {{{pts}}} }},")
        out.append("  },")
    out.append("}")
    times = shipped_times(RESOURCES / "overrides")
    out.append("-- the roads players drew in game that this data has (by time; the addon drops them from its own list)")
    out.append("ns.RoadTracksIn = {" + ",".join(f"[{t}]=true" for t in times) + "}")
    return "\n".join(out) + "\n"


def write_roads_lua(data_dir: Path, addon_dir: Path) -> Path:
    p = Path(addon_dir) / "Data" / "Roads.lua"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(roads_lua(data_dir), encoding="utf-8", newline="\n")
    return p
