"""Generate the addon's Lua data files from the local client (developer tool).

The addon ships only numbers derived from the client -- texture FileDataIDs,
map bounds, offsets -- never Blizzard files. The game draws its own textures
from those IDs.
"""

from __future__ import annotations

import io
import time
from collections import defaultdict
from pathlib import Path

from PIL import Image

from .extract import adt
from .extract.spike import ClientData
from .extract.pipeline import CONTINENTS
from .extract.tables import build_uimaps


def _header(cd: ClientData, what: str) -> str:
    return (f"-- GENERATED by `agps gen-addon-data` from client {cd.casc.version} on "
            f"{time.strftime('%Y-%m-%d')}. {what}\n-- Do not edit by hand.\nlocal _, ns = ...\n")


def minimap_lua(cd: ClientData) -> str:
    """ns.MinimapTiles[continent][tx * 64 + ty] = FileDataID of the 512x512 minimap tile."""
    lines = [_header(cd, "Minimap tile texture IDs per terrain tile."), "ns.MinimapTiles = {"]
    for cont in CONTINENTS:
        m = next(r for r in cd.table("Map") if r["ID"] == cont)
        wdt = adt.parse_wdt(cd.casc.read(m["WdtFileDataID"]))
        entries = sorted((tx * 64 + ty, t.minimap) for (tx, ty), t in wdt.tiles.items() if t.minimap)
        lines.append(f"  [{cont}] = {{")
        for i in range(0, len(entries), 8):
            lines.append("    " + " ".join(f"[{k}]={v}," for k, v in entries[i : i + 8]))
        lines.append("  },")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _image_size(cd: ClientData, fid: int, cache: dict) -> tuple[int, int]:
    if fid not in cache:
        cache[fid] = Image.open(io.BytesIO(cd.casc.read(fid))).size
    return cache[fid]


CAPITAL_FLAG = 0x100  # AreaTable.Flags[0]: set for the capital cities


def city_zone_parents(cd: ClientData, maps: dict) -> dict[int, int]:
    """City maps -> the zone around them (Undercity -> Tirisfal Glades).

    UiMap parents cities to the continent, and zone rectangles overlap, so this counts
    which zone owns the terrain chunks under the city's footprint (from the area grid).
    """
    from collections import Counter

    from .extract import adt
    from .extract.pipeline import CONTINENTS, extract_area_grid

    areas = {r["ID"]: r for r in cd.table("AreaTable")}
    zone_map = {m["areaId"]: mid for mid, m in maps.items() if m["type"] == 3 and m.get("areaId")}

    def top_zone(area):
        seen = set()
        while area and area not in seen:
            seen.add(area)
            if area in zone_map:
                return area
            area = areas.get(area, {}).get("ParentAreaID", 0)
        return None

    out = {}
    grids = {c: extract_area_grid(cd, c)[0] for c in CONTINENTS}
    for mid, m in maps.items():
        area = areas.get(m.get("areaId"))
        is_capital = area is not None and area["Flags"][0] & CAPITAL_FLAG
        if m["type"] != 3 or not is_capital or "minX" not in m or m["continent"] not in grids:
            continue
        g = grids[m["continent"]]
        r0, r1 = int((32 - m["maxX"] / adt.TILE_YD) * 16), int((32 - m["minX"] / adt.TILE_YD) * 16)
        c0, c1 = int((32 - m["maxY"] / adt.TILE_YD) * 16), int((32 - m["minY"] / adt.TILE_YD) * 16)
        counts = Counter()
        for a in g[max(r0, 0):r1 + 1, max(c0, 0):c1 + 1].ravel().tolist():
            z = top_zone(a)
            if z and z != m.get("areaId"):
                counts[z] += 1
        if counts:
            out[mid] = zone_map[counts.most_common(1)[0][0]]
    return out


def zones_lua(cd: ClientData) -> str:
    """Data/Zones.lua: the zone (its uiMap) of every ground chunk (33.3 yd) on each continent,
    from the ADTs' area ids (a subzone counts as its zone). For routes that keep out of zones
    too high for the player (Router.ZoneAt)."""
    from .extract import adt
    from .extract.pipeline import CONTINENTS, extract_area_grid

    maps = {m["id"]: m for m in build_uimaps(cd)}
    areas = {r["ID"]: r for r in cd.table("AreaTable")}
    zone_map = {m["areaId"]: mid for mid, m in maps.items() if m["type"] == 3 and m.get("areaId")}
    top: dict[int, int] = {}

    def zone_of(area):
        if area in top:
            return top[area]
        a, seen = area, set()
        while a and a not in seen:
            seen.add(a)
            if a in zone_map:
                break
            a = areas.get(a, {}).get("ParentAreaID", 0)
        top[area] = zone_map.get(a, 0)
        return top[area]

    out = [_header(cd, "Zones"),
           "-- ns.Zones[continent] = { chunk = yards, rows = { [row] = { uiMap, run, uiMap, run, ... } } }:",
           "-- row = floor((32 - x / 533.33) * 16), column = floor((32 - y / 533.33) * 16), runs from column 0;",
           "-- 0 = no zone. (Router.ZoneAt)",
           "ns.Zones = {}"]
    for cont in CONTINENTS:
        grid, _n = extract_area_grid(cd, cont)
        out.append(f"ns.Zones[{cont}] = {{ chunk = {adt.CHUNK_YD:.4f}, rows = {{")
        for r in range(grid.shape[0]):
            row = [zone_of(int(a)) if a else 0 for a in grid[r].tolist()]
            if not any(row):
                continue
            runs, cur, n = [], row[0], 0
            for z in row:
                if z == cur:
                    n += 1
                else:
                    runs += [cur, n]
                    cur, n = z, 1
            runs += [cur, n]
            out.append(f"  [{r}] = {{{','.join(map(str, runs))}}},")
        out.append("} }")
    return "\n".join(out) + "\n"


def zone_art_lua(cd: ClientData) -> str:
    """ns.Maps[uiMapID] = bounds + art tiles + explored overlays (fully revealed map)."""
    all_maps = {m["id"]: m for m in build_uimaps(cd)}
    maps = {k: m for k, m in all_maps.items() if "continent" in m}
    # The world map (Azeroth) spans continents: each continent occupies a sub-rectangle of
    # its art (UiMapAssignment with partial UiMin/UiMax).
    world_frames = defaultdict(list)
    for r in cd.table("UiMapAssignment"):
        if r["UiMin"] != [0.0, 0.0] or r["UiMax"] != [1.0, 1.0]:
            m = all_maps.get(r["UiMapID"])
            if m and m["type"] == 1 and r["MapID"] in CONTINENTS:
                world_frames[r["UiMapID"]].append(r)
    for wid in world_frames:
        maps[wid] = all_maps[wid]
    zone_parent = city_zone_parents(cd, maps)
    art_of = {r["UiMapID"]: r["UiMapArtID"] for r in cd.table("UiMapXMapArt")}
    arts = {r["ID"]: r for r in cd.table("UiMapArt")}
    styles = {r["UiMapArtStyleID"]: r for r in cd.table("UiMapArtStyleLayer") if r["LayerIndex"] == 0}
    art_tiles = defaultdict(list)
    for t in cd.table("UiMapArtTile"):
        if t["LayerIndex"] == 0:
            art_tiles[t["UiMapArtID"]].append(t)
    ov_tiles = defaultdict(list)
    for t in cd.table("WorldMapOverlayTile"):
        if t["LayerIndex"] == 0:
            ov_tiles[t["WorldMapOverlayID"]].append(t)
    overlays = defaultdict(list)
    for o in cd.table("WorldMapOverlay"):
        overlays[o["UiMapArtID"]].append(o)
    sizes: dict[int, tuple[int, int]] = {}

    out = [_header(cd, "World map art (base + explored overlays) and bounds per uiMap."),
           "-- bounds: world yards {minX, minY, maxX, maxY}; X = north, Y = west.",
           "-- tiles/overlay tiles: {fileID, x, y, w, h, texW, texH} in art pixels.",
           "ns.Maps = {"]
    for mid in sorted(maps):
        m = maps[mid]
        art_id = art_of.get(mid)
        art = arts.get(art_id)
        style = styles.get(art["UiMapArtStyleID"]) if art else None
        out.append(f"  [{mid}] = {{ name = {_lua_str(m['name'])}, type = {m['type']}, parent = {m['parent']}, "
                   f"continent = {m.get('continent', -1)}, areaId = {m.get('areaId', 0)},")
        if "minX" in m:
            out.append(f"    bounds = {{ {m['minX']:.2f}, {m['minY']:.2f}, {m['maxX']:.2f}, {m['maxY']:.2f} }},")
        if mid in zone_parent:
            out.append(f"    zoneParent = {zone_parent[mid]}, -- {maps[zone_parent[mid]]['name']}: one level up")
        if mid in world_frames:
            # [continent] = { region minX, minY, maxX, maxY, art u0, v0, u1, v1 }
            wf = ", ".join(
                f"[{r['MapID']}] = {{ {r['Region'][0]:.2f}, {r['Region'][1]:.2f}, {r['Region'][3]:.2f}, {r['Region'][4]:.2f}, "
                f"{r['UiMin'][0]:.5f}, {r['UiMin'][1]:.5f}, {r['UiMax'][0]:.5f}, {r['UiMax'][1]:.5f} }}"
                for r in sorted(world_frames[mid], key=lambda r: r["MapID"]))
            out.append(f"    worldFrames = {{ {wf} }},")
        if style:
            tw, th = style["TileWidth"], style["TileHeight"]
            out.append(f"    artW = {style['LayerWidth']}, artH = {style['LayerHeight']},")
            tiles = []
            for t in sorted(art_tiles[art_id], key=lambda t: (t["RowIndex"], t["ColIndex"])):
                w, h = _image_size(cd, t["FileDataID"], sizes)
                tiles.append(f"{{{t['FileDataID']},{t['ColIndex'] * tw},{t['RowIndex'] * th},{w},{h},{w},{h}}}")
            out.append("    tiles = { " + ", ".join(tiles) + " },")
            ovs = []
            for o in overlays.get(art_id, []):
                parts = []
                for t in sorted(ov_tiles[o["ID"]], key=lambda t: (t["RowIndex"], t["ColIndex"])):
                    texw, texh = _image_size(cd, t["FileDataID"], sizes)
                    x0, y0 = t["ColIndex"] * 256, t["RowIndex"] * 256
                    w = min(texw, o["TextureWidth"] - x0)
                    h = min(texh, o["TextureHeight"] - y0)
                    if w > 0 and h > 0:
                        parts.append(f"{{{t['FileDataID']},{o['OffsetX'] + x0},{o['OffsetY'] + y0},{w},{h},{texw},{texh}}}")
                ovs.extend(parts)
            if ovs:
                out.append("    overlays = { " + ", ".join(ovs) + " },")
        out.append("  },")
    out.append("}")
    return "\n".join(out) + "\n"


TRANSPORT_SPEED = 30.0  # yd/s, roughly how fast zeppelins and boats travel
TRANSPORT_WAIT = 120.0  # s, average wait for the next departure


def transport_periods() -> dict[int, float]:
    """Each transport's full cycle (seconds) by its TaxiPath id, from the CMaNGOS dump under
    data/thirdparty (its `transports` periods; gameobject_template type 15's data0 is the
    path). Empty without the dump."""
    import gzip
    import re

    from .paths import data_dir

    dump = data_dir() / "thirdparty" / "cmangos-classic-db" / "ClassicDB_1_12_1_z2815.sql.gz"
    if not dump.exists():
        return {}
    txt = gzip.open(dump, "rt", encoding="utf-8", errors="replace").read()
    m = re.search(r"INSERT INTO `transports` VALUES (.*?);\n", txt, re.S)
    period = {int(e): int(ms) / 1000.0 for e, ms in re.findall(r"\((\d+),'(?:[^'\\]|\\.)*',(\d+)\)", m.group(1))} if m else {}
    out = {}
    for m in re.finditer(r"INSERT INTO `gameobject_template` VALUES (.*?);\n", txt, re.S):
        for e, path in re.findall(r"\((\d+),15,\d+,'(?:[^'\\]|\\.)*',\d+,\d+,\d+,[\d.]+,(\d+),", m.group(1)):
            if int(e) in period:
                out[int(path)] = period[int(e)]
    return out


def transports_lua(cd: ClientData) -> str:
    """ns.Transports = { {cont1, x1, y1, cont2, x2, y2, seconds, kind, name1, name2}, ... }

    From transport TaxiPaths: each has exactly two docks, the nodes where the ship waits
    (Delay >= 30). seconds = ride (path length between the docks / TRANSPORT_SPEED) plus an
    average wait. kind: "zeppelin" (docks high up) or "boat".
    """
    import math

    from .extract.pipeline import CONTINENTS, extract_area_grid, town_labels

    towns = defaultdict(list)
    for cont in CONTINENTS:
        grid, _ = extract_area_grid(cd, cont)
        towns[cont] = town_labels(cd, cont, grid)
    zones = {m["areaId"]: m["name"] for m in build_uimaps(cd) if m.get("areaId") and m["type"] == 3}

    def place_name(cont, x, y):
        best = min(towns[cont], key=lambda t: (t["wx"] - x) ** 2 + (t["wy"] - y) ** 2)
        zone = next((zones[a] for a in best["ancestors"] if a in zones), None)
        return f"{best['name']}, {zone}" if zone and zone != best["name"] else best["name"]

    nodes = defaultdict(list)
    for n in cd.table("TaxiPathNode"):
        nodes[n["PathID"]].append(n)
    periods = transport_periods()
    seen, rows = set(), []
    for pid, ns_ in sorted(nodes.items()):
        ns_ = sorted(ns_, key=lambda n: n["NodeIndex"])
        stops, keys = [], set()
        for i, n in enumerate(ns_):
            if n["Delay"] >= 30:
                key = (n["ContinentID"], round(n["Loc"][0] / 20), round(n["Loc"][1] / 20))
                if key not in keys:
                    keys.add(key)
                    stops.append((i, n))
        if len(stops) != 2:
            continue
        (i1, a), (i2, b) = stops
        if a["ContinentID"] not in CONTINENTS or b["ContinentID"] not in CONTINENTS:
            continue
        def along(js, ns_=ns_):  # yards along the path over these legs (same-continent ones only)
            d = 0.0
            for j in js:
                p, q = ns_[j]["Loc"], ns_[(j + 1) % len(ns_)]["Loc"]
                if ns_[j]["ContinentID"] == ns_[(j + 1) % len(ns_)]["ContinentID"]:
                    d += math.dist(p[:2], q[:2])
            return d
        dist = along(range(i1, i2))  # from the first dock to the second
        back = along(list(range(i2, len(ns_))) + list(range(0, i1)))  # and on round to the first
        # the timetable: the whole cycle (the server's when known), the waits at the docks, and
        # the rides between (the moving time shared by length)
        wait1, wait2 = a["Delay"], b["Delay"]
        cycle = periods.get(pid) or (dist + back) / TRANSPORT_SPEED + wait1 + wait2
        moving = max(cycle - wait1 - wait2, 1.0)
        ride1, ride2 = moving * dist / max(dist + back, 1.0), moving * back / max(dist + back, 1.0)
        key = tuple(sorted([(a["ContinentID"], round(a["Loc"][0]), round(a["Loc"][1])),
                            (b["ContinentID"], round(b["Loc"][0]), round(b["Loc"][1]))]))
        if key in seen:
            continue
        seen.add(key)
        kind = "zeppelin" if a["Loc"][2] > 30 and b["Loc"][2] > 30 else "boat"
        secs = dist / TRANSPORT_SPEED + TRANSPORT_WAIT
        (c1, x1, y1), (c2, x2, y2) = (a["ContinentID"], *a["Loc"][:2]), (b["ContinentID"], *b["Loc"][:2])
        rows.append(f'  {{ {c1}, {x1:.1f}, {y1:.1f}, {c2}, {x2:.1f}, {y2:.1f}, {secs:.0f}, "{kind}", '
                    f'{_lua_str(place_name(c1, x1, y1))}, {_lua_str(place_name(c2, x2, y2))}, '
                    f'cycle = {cycle:.1f}, ride1 = {ride1:.1f}, ride2 = {ride2:.1f}, wait1 = {wait1}, wait2 = {wait2}'
                    f'{", server = true" if pid in periods else ""} }},')
    # The Deeprun Tram: its own map (369), in by an area trigger at each end (Stormwind, Ironforge)
    triggers = {r["ID"]: r for r in cd.table("AreaTrigger")}
    a, b = triggers.get(TRAM_TRIGGERS[0]), triggers.get(TRAM_TRIGGERS[1])
    if a and b:
        (x1, y1), (x2, y2) = a["Pos"][:2], b["Pos"][:2]
        rows.append(f'  {{ {a["ContinentID"]}, {x1:.1f}, {y1:.1f}, {b["ContinentID"]}, {x2:.1f}, {y2:.1f}, {TRAM_SECONDS:.0f}, '
                    f'"tram", "Stormwind City", "Ironforge", "Deeprun Tram" }},')
    return "\n".join([_header(cd, "Zeppelins and boats: docks, ride + average wait; the timetable: cycle (s), ride1 (dock 1"
                              " to 2), ride2 (back round), wait1 / wait2 (at each dock). And the Deeprun Tram."),
                      "ns.Transports = {", *rows, "}"]) + "\n"


# The Deeprun Tram's ways in (AreaTrigger ids: Stormwind's, Ironforge's) and its time end to end:
# the loading screens (2 x 5 s), the walks between the way in and the platforms (about 90 yd at
# each end), the wait for a train (two trains, one leaving each station every 71.7 s: 36 s on
# average) and the ride (58.6 s between the stations; the cars' TransportAnimation: a 143.3 s loop).
TRAM_TRIGGERS = (2173, 2175)
TRAM_SECONDS = 2 * 5 + 2 * 90 / 7 + 36 + 58.6


def flights_lua(cd: ClientData) -> str:
    """ns.Flights = { {fromNode, toNode, yards}, ... }

    The direct flights between flight masters (TaxiPath, both ends a flight master on the
    same continent), with the length flown along the path's points (TaxiPathNode). The addon
    chains them into connecting flights between the flight masters a character knows.
    """
    import math

    from .extract.pipeline import taxi_pois

    masters = {p["id"]: p["continent"] for p in taxi_pois(cd)}
    points = defaultdict(list)
    for n in cd.table("TaxiPathNode"):
        points[n["PathID"]].append(n)
    rows = []
    for p in sorted(cd.table("TaxiPath"), key=lambda r: r["ID"]):
        a, b = p["FromTaxiNode"], p["ToTaxiNode"]
        if a not in masters or b not in masters or masters[a] != masters[b] or a == b:
            continue
        pts = sorted(points.get(p["ID"], []), key=lambda n: n["NodeIndex"])
        yards = sum(math.dist(pts[i]["Loc"][:2], pts[i + 1]["Loc"][:2]) for i in range(len(pts) - 1)
                    if pts[i]["ContinentID"] == pts[i + 1]["ContinentID"])
        if yards <= 0:
            continue
        rows.append(f"  {{ {a}, {b}, {yards:.0f} }},")
    return "\n".join([_header(cd, "Direct flights between flight masters: from node, to node, yards flown."),
                      "ns.Flights = {", *rows, "}"]) + "\n"


def pois_lua(cd: ClientData) -> str:
    """ns.Pois[continent] = { {kind, x, y, name, extra}, ... }
    kind: 1 flight master (extra = nodeID, faction "A"/"H"/"AH", and the city level it's down
    in, if it is: Undercity's), 2 map point of interest (extra = importance), 3 town/place
    label (extra = parent zone areaId)."""
    from .extract.pipeline import CONTINENTS, area_pois, extract_area_grid, taxi_pois, town_labels

    rows: dict[int, list[str]] = {c: [] for c in CONTINENTS}
    for p in taxi_pois(cd):
        fac = "".join(f[0].upper() for f in sorted(p["factions"]))
        level = underground_level(cd, p)
        tail = f",{level}" if level else ""
        rows[p["continent"]].append(f'{{1,{p["wx"]},{p["wy"]},{_lua_str(p["name"])},{p["id"]},"{fac}"{tail}}}')
    for p in area_pois(cd):
        rows[p["continent"]].append(f'{{2,{p["wx"]},{p["wy"]},{_lua_str(p["name"])},{p["importance"]}}}')
    for cont in CONTINENTS:
        grid, _ = extract_area_grid(cd, cont)
        for p in town_labels(cd, cont, grid):
            zone = p["ancestors"][-1] if p["ancestors"] else 0
            rows[cont].append(f'{{3,{p["wx"]},{p["wy"]},{_lua_str(p["name"])},{zone}}}')
    out = [_header(cd, "Points of interest: flight masters, map POIs, place labels."), "ns.Pois = {"]
    for cont, items in rows.items():
        out.append(f"  [{cont}] = {{")
        for i in range(0, len(items), 4):
            out.append("    " + " ".join(r + "," for r in items[i : i + 4]))
        out.append("  },")
    out.append("}")
    # Named building areas (inns, taverns, halls): where they stand. The hearthstone's bind
    # location is often an inn's own name ("Gallows' End Tavern"), which isn't a map label.
    spots = area_spots(cd)
    out.append("-- ns.AreaSpots[building area name] = { continent, x, y }")
    out.append("ns.AreaSpots = {")
    for name in sorted(spots):
        c, x, y = spots[name]
        out.append(f"  [{_lua_str(name)}] = {{ {c}, {x:.1f}, {y:.1f} }},")
    out.append("}")
    return "\n".join(out) + "\n"


UNDERGROUND_YD = 10.0  # a flight master this far below the ground over it is down in a city


def underground_level(cd: ClientData, p: dict):
    """The city level (Undercity: 10001) a flight master stands down in, else None: it's on a
    city level's base continent, near the city, and well below the ground there."""
    import math

    import numpy as np

    from .cities import UNDERCITY_ID, _ground

    if p["continent"] != 0 or "wz" not in p:
        return None
    if math.hypot(p["wx"] - 1600.0, p["wy"] - 240.0) > 450:  # (the Undercity's area)
        return None
    x, y = p["wx"], p["wy"]
    height, _ = _ground(cd, x - 4, x + 4, y - 4, y + 4, 2.0)
    ground = np.nanmax(height) if np.isfinite(height).any() else None
    if ground is not None and p["wz"] < ground - UNDERGROUND_YD:
        return UNDERCITY_ID
    return None


def area_spots(cd: ClientData) -> dict[str, tuple[int, float, float]]:
    """Name of each area inside a building (WMOAreaTable: its own name, or its AreaTable
    area's) -> the building's position (first placement found on a covered continent)."""
    from .extract.pipeline import CONTINENTS
    from .interiors import placements, read_wmo

    area_names = {r["ID"]: r["AreaName_lang"] for r in cd.table("AreaTable")}
    names_by: dict[tuple[int, int], set[str]] = defaultdict(set)  # (WMOID, NameSetID)
    for r in cd.table("WMOAreaTable"):
        for name in (r["AreaName_lang"], area_names.get(r["AreaTableID"])):
            if name:
                names_by[(r["WMOID"], r["NameSetID"])].add(name)
    spots: dict[str, tuple[int, float, float]] = {}
    wmo_ids: dict[int, int] = {}  # placed file -> WMOID (read once per file)
    for cont in CONTINENTS:
        for p in placements(cd, cont):
            if p.wmo not in wmo_ids:
                w = read_wmo(cd, p.wmo)
                wmo_ids[p.wmo] = w.wmo_id if w else 0
            # the same building model is used in many places, each with its own names
            for name in names_by.get((wmo_ids[p.wmo], p.name_set), ()):
                spots.setdefault(name, (cont, p.x, p.y))
    return spots


def _lua_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def generate(cd: ClientData, addon_dir: Path) -> list[Path]:
    data = addon_dir / "Data"
    data.mkdir(parents=True, exist_ok=True)
    written = []
    from .interiors import build as build_interiors, interiors_lua

    interiors = interiors_lua(cd, build_interiors(cd))
    from .roads.terrain import terrain_lua
    from .cities import cities_lua
    from .caves import caves_lua
    from .capitals import capitals_lua

    for name, text in (("Minimap.lua", minimap_lua(cd)), ("Maps.lua", zone_art_lua(cd)), ("Interiors.lua", interiors),
                       ("Pois.lua", pois_lua(cd)), ("Terrain.lua", terrain_lua(cd)),
                       ("Transports.lua", transports_lua(cd)), ("Flights.lua", flights_lua(cd)),
                       ("Cities.lua", cities_lua(cd)), ("Caves.lua", caves_lua(cd)), ("Capitals.lua", capitals_lua(cd)),
                       ("Zones.lua", zones_lua(cd))):
        p = data / name
        p.write_text(text, encoding="utf-8", newline="\n")
        written.append(p)
    from .paths import data_dir
    from .roads.export import write_roads_lua

    from .hostile import DUMP, hostile_lua

    if (data_dir() / DUMP).exists():  # (the other faction's guards: NPC data under data/thirdparty)
        p = data / "Hostile.lua"
        p.write_text(hostile_lua(cd, data_dir()), encoding="utf-8", newline="\n")
        written.append(p)
        # (dungeons and raids: their entrances and bosses come from the same NPC data)
        from .instances import build_all as build_instances, instances_lua

        p = data / "Instances.lua"
        p.write_text(instances_lua(cd, build_instances(cd, data_dir())), encoding="utf-8", newline="\n")
        written.append(p)

    written.append(write_roads_lua(data_dir(), addon_dir))
    return written
