"""Where each faction's guards stand and walk, for routes that keep players of the other
faction away from them (Data/Hostile.lua).

Guards: NPCs flagged as guards (or named like them: Grunt, Deathguard, Sentinel, ...) of a
faction hostile to one side only (the client's FactionTemplate EnemyGroup: 2 Alliance
players, 4 Horde players), from the NPC spawn and patrol data under data/thirdparty.
Each spawn (and each point of a patrol) becomes a circle of GUARD_YD, plus how far the NPC
wanders; circles close together are merged into one.
"""

from __future__ import annotations

import gzip
import math
import re
from pathlib import Path

GUARD_FLAG = 0x400  # creature_template.ExtraFlags: a guard
GUARD_NAME = re.compile(r"\b(Guard|Guardian|Grunt|Deathguard|Sentinel|Bluffwatcher|Brave|Protector|"
                        r"Mountaineer|Watchman|Defender|Warden|Peacekeeper|Enforcer|Footman|Rifleman)\b")
GUARD_YD = 35.0  # about how far a guard of a much higher level notices a player
CELL_YD = 20.0  # circles within a cell of this size are one
GROUP_ALLIANCE, GROUP_HORDE = 2, 4
DUMP = Path("thirdparty") / "cmangos-classic-db" / "ClassicDB_1_12_1_z2815.sql.gz"


def _tuples(s: str):
    i, n = 0, len(s)
    while i < n:
        if s[i] != "(":
            i += 1
            continue
        i += 1
        vals, cur, q = [], [], False
        while i < n:
            c = s[i]
            if q:
                if c == "\\":
                    cur.append(s[i + 1])
                    i += 2
                    continue
                if c == "'":
                    if i + 1 < n and s[i + 1] == "'":
                        cur.append("'")
                        i += 2
                        continue
                    q = False
                    i += 1
                    continue
                cur.append(c)
                i += 1
                continue
            if c == "'":
                q = True
            elif c == ",":
                vals.append("".join(cur))
                cur = []
            elif c == ")":
                vals.append("".join(cur))
                i += 1
                break
            else:
                cur.append(c)
            i += 1
        yield vals


def _rows(txt: str, table: str):
    m = re.search(r"CREATE TABLE `%s` \((.*?)\n\) ENGINE" % table, txt, re.S)
    cols = re.findall(r"^\s*`(\w+)`", m.group(1), re.M)
    for m in re.finditer(r"INSERT INTO `%s` (?:\([^)]*\) )?VALUES\s*(.*?);\n" % table, txt, re.S):
        for vals in _tuples(m.group(1)):
            if len(vals) == len(cols):
                yield dict(zip(cols, vals))


def guard_points(data_dir: Path, faction_templates: dict[int, dict]) -> dict[int, dict[str, list]]:
    """{ continent: { "A": [(x, y, r)], "H": [...] } }: "A" is dangerous to Alliance players."""
    txt = gzip.open(Path(data_dir) / DUMP, "rt", encoding="utf-8", errors="replace").read()
    side = {}  # entry -> "A" / "H"
    for r in _rows(txt, "creature_template"):
        guard = int(r["ExtraFlags"]) & GUARD_FLAG or GUARD_NAME.search(r["Name"])
        ft = faction_templates.get(int(r["Faction"]))
        if not guard or not ft:
            continue
        enemy = ft["EnemyGroup"]
        if enemy & GROUP_ALLIANCE and not enemy & GROUP_HORDE:
            side[r["Entry"]] = "A"
        elif enemy & GROUP_HORDE and not enemy & GROUP_ALLIANCE:
            side[r["Entry"]] = "H"
    out: dict[int, dict[str, list]] = {}
    spawn = {}  # guid -> (map, side)
    for r in _rows(txt, "creature"):
        s = side.get(r["id"])
        mp = int(r["map"])
        if s and mp in (0, 1):
            x, y = float(r["position_x"]), float(r["position_y"])
            out.setdefault(mp, {"A": [], "H": []})[s].append((x, y, GUARD_YD + float(r["spawndist"] or 0)))
            spawn[r["guid"]] = (mp, s)
    for r in _rows(txt, "creature_movement"):  # (patrols: each point)
        k = spawn.get(r["Id"])
        if k:
            out[k[0]][k[1]].append((float(r["PositionX"]), float(r["PositionY"]), GUARD_YD))
    return out


def merge(points: list) -> list:
    """Circles close together as one (the biggest reach in each CELL_YD cell, at the cell's
    points' middle)."""
    cells: dict = {}
    for x, y, r in points:
        k = (math.floor(x / CELL_YD), math.floor(y / CELL_YD))
        c = cells.setdefault(k, [0.0, 0.0, 0, 0.0])
        c[0] += x
        c[1] += y
        c[2] += 1
        c[3] = max(c[3], r)
    return [(c[0] / c[2], c[1] / c[2], c[3] + CELL_YD / 2) for c in cells.values()]


def hostile_lua(cd, data_dir: Path) -> str:
    ft = {r["ID"]: r for r in cd.table("FactionTemplate")}
    pts = guard_points(data_dir, ft)
    out = [f"-- GENERATED by `agps gen-addon-data` from client {cd.casc.version}. Do not edit by hand.",
           "-- Guards per faction: circles { x, y, reach, ... } in world yards; A: dangerous to Alliance",
           "-- players (the Horde's guards), H: to Horde players.",
           "local _, ns = ...", "ns.Hostile = {"]
    for cont in sorted(pts):
        out.append(f"  [{cont}] = {{")
        for s in ("A", "H"):
            circles = merge(pts[cont][s])
            flat = ",".join(f"{x:.0f},{y:.0f},{r:.0f}" for x, y, r in sorted(circles))
            out.append(f"    {s} = {{{flat}}},")
        out.append("  },")
    out.append("}")
    return "\n".join(out) + "\n"
