-- Generated by `agps import-shared` / `agps pins` (app/azerothgps/pins.py) from
-- overrides/pins.json: the pins players shared (Pins.lua), shown to everyone. Don't edit by hand.
local _, ns = ...
ns.SharedPins = {
}
ns.PinsIn = { }
