-- GENERATED by `agps gen-addon-data` from client 1.60.1.70009 on 2026-09-26. Zeppelins and boats: docks, ride + average wait.
-- Do not edit by hand.
local _, ns = ...

ns.Transports = {
  { 1, -1005.6, -3841.6, 0, -14277.7, 582.9, 213, "boat", "Ratchet, The Barrens", "Booty Bay, Stranglethorn Vale" },
  { 0, -12464.0, 231.6, 1, 1360.9, -4631.3, 201, "zeppelin", "Grom'gol Base Camp, Stranglethorn Vale", "Jaggedswine Farm, Durotar" },
  { 0, -3905.2, -585.8, 1, -4016.4, -4740.6, 201, "boat", "Menethil Harbor, Wetlands", "Theramore Isle, Dustwallow Marsh" },
  { 1, 8532.0, 1023.7, 1, 6594.4, 759.8, 194, "boat", "Rut'theran Village, Teldrassil", "Auberdine, Darkshore" },
  { 0, -3709.5, -575.1, 1, 6406.2, 823.1, 192, "boat", "Menethil Harbor, Wetlands", "The Long Wash, Darkshore" },
  { 0, -12406.9, 211.8, 0, 2062.6, 235.3, 666, "zeppelin", "Grom'gol Base Camp, Stranglethorn Vale", "Brill, Tirisfal Glades" },
  { 1, 1318.1, -4658.0, 0, 2062.4, 293.0, 230, "zeppelin", "Jaggedswine Farm, Durotar", "Brill, Tirisfal Glades" },
  { 1, -4197.3, 3286.6, 1, -4347.8, 2444.4, 150, "boat", "Feathermoon Stronghold, Feralas", "The Forgotten Coast, Feralas" },
  { 1, -6932.6, -4950.8, 0, -8232.3, -5800.8, 172, "boat", "Steamwheedle Port, Tanaris", "Eastwind Shore, Riverglades" },
  { 0, 544.8, 424.2, 2991, 1848.3, 569.1, 210, "zeppelin", "Old Dalaran Ruins, Alterac Mountains", "Valanaar Skydocks, Zephras Isle" },
  { 1, -802.0, 366.5, 2991, 1952.5, 1019.1, 194, "zeppelin", "Camp Gev'rek, Mulgore", "Fairweather Stables, Zephras Isle" },
  { 1, 6548.3, 942.2, 0, -8654.5, 1344.4, 172, "boat", "The Long Wash, Darkshore", "Stormwind Harbor, Stormwind City" },
}
