-- GENERATED by `agps gen-addon-data` from client 1.60.1.70009 on 2026-09-28. Zeppelins and boats: docks, ride + average wait; the timetable: cycle (s), ride1 (dock 1 to 2), ride2 (back round), wait1 / wait2 (at each dock).
-- Do not edit by hand.
local _, ns = ...

ns.Transports = {
  { 1, -1005.6, -3841.6, 0, -14277.7, 582.9, 213, "boat", "Ratchet, The Barrens", "Booty Bay, Stranglethorn Vale", cycle = 350.8, ride1 = 110.3, ride2 = 120.5, wait1 = 60, wait2 = 60, server = true },
  { 0, -12464.0, 231.6, 1, 1360.9, -4631.3, 201, "zeppelin", "Grom'gol Base Camp, Stranglethorn Vale", "Jaggedswine Farm, Durotar", cycle = 303.5, ride1 = 110.0, ride2 = 73.4, wait1 = 60, wait2 = 60, server = true },
  { 0, -3905.2, -585.8, 1, -4016.4, -4740.6, 201, "boat", "Menethil Harbor, Wetlands", "Theramore Isle, Dustwallow Marsh", cycle = 329.3, ride1 = 102.7, ride2 = 106.7, wait1 = 60, wait2 = 60, server = true },
  { 1, 8532.0, 1023.7, 1, 6594.4, 759.8, 194, "boat", "Rut'theran Village, Teldrassil", "Auberdine, Darkshore", cycle = 316.3, ride1 = 96.4, ride2 = 99.9, wait1 = 60, wait2 = 60, server = true },
  { 0, -3709.5, -575.1, 1, 6406.2, 823.1, 192, "boat", "Menethil Harbor, Wetlands", "The Long Wash, Darkshore", cycle = 295.6, ride1 = 96.4, ride2 = 79.2, wait1 = 60, wait2 = 60, server = true },
  { 0, -12406.9, 211.8, 0, 2062.6, 235.3, 666, "zeppelin", "Grom'gol Base Camp, Stranglethorn Vale", "Brill, Tirisfal Glades", cycle = 333.0, ride1 = 106.5, ride2 = 106.5, wait1 = 60, wait2 = 60, server = true },
  { 1, 1318.1, -4658.0, 0, 2062.4, 293.0, 230, "zeppelin", "Jaggedswine Farm, Durotar", "Brill, Tirisfal Glades", cycle = 356.3, ride1 = 137.1, ride2 = 99.2, wait1 = 60, wait2 = 60, server = true },
  { 1, -4197.3, 3286.6, 1, -4347.8, 2444.4, 150, "boat", "Feathermoon Stronghold, Feralas", "The Forgotten Coast, Feralas", cycle = 317.0, ride1 = 41.8, ride2 = 185.3, wait1 = 30, wait2 = 60, server = true },
  { 1, -6932.6, -4950.8, 0, -8232.3, -5800.8, 172, "boat", "Steamwheedle Port, Tanaris", "Eastwind Shore, Riverglades", cycle = 225.0, ride1 = 52.0, ride2 = 52.9, wait1 = 60, wait2 = 60 },
  { 0, 544.8, 424.2, 2991, 1848.3, 569.1, 210, "zeppelin", "Old Dalaran Ruins, Alterac Mountains", "Valanaar Skydocks, Zephras Isle", cycle = 319.1, ride1 = 89.7, ride2 = 109.4, wait1 = 60, wait2 = 60 },
  { 1, -802.0, 366.5, 2991, 1952.5, 1019.1, 194, "zeppelin", "Camp Gev'rek, Mulgore", "Fairweather Stables, Zephras Isle", cycle = 307.3, ride1 = 74.0, ride2 = 143.3, wait1 = 60, wait2 = 30 },
  { 1, 6548.3, 942.2, 0, -8654.5, 1344.4, 172, "boat", "The Long Wash, Darkshore", "Stormwind Harbor, Stormwind City", cycle = 214.6, ride1 = 52.4, ride2 = 42.2, wait1 = 60, wait2 = 60 },
}
